name        : guile
version     : 2.0.11
release     : 3
source      :
    - http://ftp.gnu.org/pub/gnu/guile/guile-2.0.11.tar.gz : e6786c934346fa2e38e46d8d81a622bb1c16d130153523f6129fcd79ef1fb040
homepage    : http://www.gnu.org/software/guile
license     :
    - LGPL-3.0
summary     : GNU Ubiquitous Intelligent Language for Extensions
builddeps   :
    - libunistring-devel
    - libunistring-32bit-devel
    - bdwgc-devel
    - bdwgc-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - libtool-32bit-devel
    - gmp-32bit-devel
    - pkgconfig32(libffi)
emul32      : yes
description : |
    Guile is the official extension language for GNU, designed to help programmers create flexiable applications by allowing extension through plug-ins, modules, or scripts.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
