name       : guile
version    : 2.0.13
release    : 4
source     :
    - http://ftp.gnu.org/pub/gnu/guile/guile-2.0.13.tar.gz : ee8073c4582bb4f06412452fdf5dd185aae607441f1313c824f44bdd668b0bde
homepage   : http://www.gnu.org/software/guile
license    : LGPL-3.0
component  : programming
emul32     : yes
summary    : GNU Ubiquitous Intelligent Language for Extensions
builddeps  :
    - pkgconfig32(libffi)
    - bdwgc-32bit-devel
    - gmp-32bit-devel
    - libtool-32bit-devel
    - libunistring-32bit-devel
description: |
    Guile is the official extension language for GNU, designed to help programmers create flexiable applications by allowing extension through plug-ins, modules, or scripts.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
